version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3050:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8085:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: filippo
      MYSQL_PASSWORD: filippo123
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d # 👈 qui monti gli script SQL se vuoi

volumes:
  db_data:
