services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3050:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev --port=3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8085:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: naboo
      MYSQL_USER: filippo
      MYSQL_PASSWORD: filippo123
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
